/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceCategoriesRouteImport } from './routes/service-categories'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NewsBlogRouteImport } from './routes/news-blog'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as JobSeekersRouteImport } from './routes/job-seekers'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as BookingRequestsRouteImport } from './routes/booking-requests'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as BookingRequestsIndexRouteImport } from './routes/booking-requests.index'
import { Route as VendorsIdRouteImport } from './routes/vendors.$id'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'
import { Route as BookingRequestsIdRouteImport } from './routes/booking-requests.$id'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCategoriesRoute = ServiceCategoriesRouteImport.update({
  id: '/service-categories',
  path: '/service-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsBlogRoute = NewsBlogRouteImport.update({
  id: '/news-blog',
  path: '/news-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekersRoute = JobSeekersRouteImport.update({
  id: '/job-seekers',
  path: '/job-seekers',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRequestsRoute = BookingRequestsRouteImport.update({
  id: '/booking-requests',
  path: '/booking-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorsRoute,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeesRoute,
} as any)
const BookingRequestsIndexRoute = BookingRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingRequestsRoute,
} as any)
const VendorsIdRoute = VendorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VendorsRoute,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeesRoute,
} as any)
const BookingRequestsIdRoute = BookingRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BookingRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-requests': typeof BookingRequestsRouteWithChildren
  '/coupons': typeof CouponsRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/employers': typeof EmployersRoute
  '/finance': typeof FinanceRoute
  '/job-seekers': typeof JobSeekersRoute
  '/jobs': typeof JobsRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/news-blog': typeof NewsBlogRoute
  '/orders': typeof OrdersRoute
  '/pages': typeof PagesRoute
  '/reviews': typeof ReviewsRoute
  '/service-categories': typeof ServiceCategoriesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/booking-requests/$id': typeof BookingRequestsIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/booking-requests/': typeof BookingRequestsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coupons': typeof CouponsRoute
  '/dashboard': typeof DashboardRoute
  '/employers': typeof EmployersRoute
  '/finance': typeof FinanceRoute
  '/job-seekers': typeof JobSeekersRoute
  '/jobs': typeof JobsRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/news-blog': typeof NewsBlogRoute
  '/orders': typeof OrdersRoute
  '/pages': typeof PagesRoute
  '/reviews': typeof ReviewsRoute
  '/service-categories': typeof ServiceCategoriesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/booking-requests/$id': typeof BookingRequestsIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/booking-requests': typeof BookingRequestsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/vendors': typeof VendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-requests': typeof BookingRequestsRouteWithChildren
  '/coupons': typeof CouponsRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/employers': typeof EmployersRoute
  '/finance': typeof FinanceRoute
  '/job-seekers': typeof JobSeekersRoute
  '/jobs': typeof JobsRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/news-blog': typeof NewsBlogRoute
  '/orders': typeof OrdersRoute
  '/pages': typeof PagesRoute
  '/reviews': typeof ReviewsRoute
  '/service-categories': typeof ServiceCategoriesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/booking-requests/$id': typeof BookingRequestsIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/booking-requests/': typeof BookingRequestsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-requests'
    | '/coupons'
    | '/dashboard'
    | '/employees'
    | '/employers'
    | '/finance'
    | '/job-seekers'
    | '/jobs'
    | '/listings'
    | '/login'
    | '/messages'
    | '/news-blog'
    | '/orders'
    | '/pages'
    | '/reviews'
    | '/service-categories'
    | '/services'
    | '/settings'
    | '/users'
    | '/vendors'
    | '/booking-requests/$id'
    | '/employees/$id'
    | '/vendors/$id'
    | '/booking-requests/'
    | '/employees/'
    | '/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coupons'
    | '/dashboard'
    | '/employers'
    | '/finance'
    | '/job-seekers'
    | '/jobs'
    | '/listings'
    | '/login'
    | '/messages'
    | '/news-blog'
    | '/orders'
    | '/pages'
    | '/reviews'
    | '/service-categories'
    | '/services'
    | '/settings'
    | '/users'
    | '/booking-requests/$id'
    | '/employees/$id'
    | '/vendors/$id'
    | '/booking-requests'
    | '/employees'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/booking-requests'
    | '/coupons'
    | '/dashboard'
    | '/employees'
    | '/employers'
    | '/finance'
    | '/job-seekers'
    | '/jobs'
    | '/listings'
    | '/login'
    | '/messages'
    | '/news-blog'
    | '/orders'
    | '/pages'
    | '/reviews'
    | '/service-categories'
    | '/services'
    | '/settings'
    | '/users'
    | '/vendors'
    | '/booking-requests/$id'
    | '/employees/$id'
    | '/vendors/$id'
    | '/booking-requests/'
    | '/employees/'
    | '/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRequestsRoute: typeof BookingRequestsRouteWithChildren
  CouponsRoute: typeof CouponsRoute
  DashboardRoute: typeof DashboardRoute
  EmployeesRoute: typeof EmployeesRouteWithChildren
  EmployersRoute: typeof EmployersRoute
  FinanceRoute: typeof FinanceRoute
  JobSeekersRoute: typeof JobSeekersRoute
  JobsRoute: typeof JobsRoute
  ListingsRoute: typeof ListingsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NewsBlogRoute: typeof NewsBlogRoute
  OrdersRoute: typeof OrdersRoute
  PagesRoute: typeof PagesRoute
  ReviewsRoute: typeof ReviewsRoute
  ServiceCategoriesRoute: typeof ServiceCategoriesRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  VendorsRoute: typeof VendorsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-categories': {
      id: '/service-categories'
      path: '/service-categories'
      fullPath: '/service-categories'
      preLoaderRoute: typeof ServiceCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-blog': {
      id: '/news-blog'
      path: '/news-blog'
      fullPath: '/news-blog'
      preLoaderRoute: typeof NewsBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seekers': {
      id: '/job-seekers'
      path: '/job-seekers'
      fullPath: '/job-seekers'
      preLoaderRoute: typeof JobSeekersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-requests': {
      id: '/booking-requests'
      path: '/booking-requests'
      fullPath: '/booking-requests'
      preLoaderRoute: typeof BookingRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/employees/': {
      id: '/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/booking-requests/': {
      id: '/booking-requests/'
      path: '/'
      fullPath: '/booking-requests/'
      preLoaderRoute: typeof BookingRequestsIndexRouteImport
      parentRoute: typeof BookingRequestsRoute
    }
    '/vendors/$id': {
      id: '/vendors/$id'
      path: '/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof VendorsIdRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/booking-requests/$id': {
      id: '/booking-requests/$id'
      path: '/$id'
      fullPath: '/booking-requests/$id'
      preLoaderRoute: typeof BookingRequestsIdRouteImport
      parentRoute: typeof BookingRequestsRoute
    }
  }
}

interface BookingRequestsRouteChildren {
  BookingRequestsIdRoute: typeof BookingRequestsIdRoute
  BookingRequestsIndexRoute: typeof BookingRequestsIndexRoute
}

const BookingRequestsRouteChildren: BookingRequestsRouteChildren = {
  BookingRequestsIdRoute: BookingRequestsIdRoute,
  BookingRequestsIndexRoute: BookingRequestsIndexRoute,
}

const BookingRequestsRouteWithChildren = BookingRequestsRoute._addFileChildren(
  BookingRequestsRouteChildren,
)

interface EmployeesRouteChildren {
  EmployeesIdRoute: typeof EmployeesIdRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesIdRoute: EmployeesIdRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

interface VendorsRouteChildren {
  VendorsIdRoute: typeof VendorsIdRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

const VendorsRouteChildren: VendorsRouteChildren = {
  VendorsIdRoute: VendorsIdRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}

const VendorsRouteWithChildren =
  VendorsRoute._addFileChildren(VendorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRequestsRoute: BookingRequestsRouteWithChildren,
  CouponsRoute: CouponsRoute,
  DashboardRoute: DashboardRoute,
  EmployeesRoute: EmployeesRouteWithChildren,
  EmployersRoute: EmployersRoute,
  FinanceRoute: FinanceRoute,
  JobSeekersRoute: JobSeekersRoute,
  JobsRoute: JobsRoute,
  ListingsRoute: ListingsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NewsBlogRoute: NewsBlogRoute,
  OrdersRoute: OrdersRoute,
  PagesRoute: PagesRoute,
  ReviewsRoute: ReviewsRoute,
  ServiceCategoriesRoute: ServiceCategoriesRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  VendorsRoute: VendorsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
